### ISSUE TITLE
One question about multivalue features

### ISSUE THREAD

**Issue by shinesun130** [Lapis-Hong/wide_deep#1]
I see you process multivalue features in dataset.py, but not used in feature column, is that right?
How can the multivalue features be used ?

waiting for the response~
Thanks a lot!

**Comment by Lapis-Hong** [comment]
Thanks for posting issue, actually tf.feature column can deal with multivalve feature as something like multihot, so as long as you process the input, it is used in feature column.

**Comment by shinesun130** [comment]
Thank you !
